//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sign.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzureKeyVaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureKeyVaultResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sign.Cli.AzureKeyVaultResources", typeof(AzureKeyVaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the certificate in Azure Key Vault..
        /// </summary>
        internal static string CertificateOptionDescription {
            get {
                return ResourceManager.GetString("CertificateOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID to authenticate to Azure Key Vault..
        /// </summary>
        internal static string ClientIdOptionDescription {
            get {
                return ResourceManager.GetString("ClientIdOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret to authenticate to Azure Key Vault..
        /// </summary>
        internal static string ClientSecretOptionDescription {
            get {
                return ResourceManager.GetString("ClientSecretOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Azure Key Vault..
        /// </summary>
        internal static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) to sign..
        /// </summary>
        internal static string FilesArgumentDescription {
            get {
                return ResourceManager.GetString("FilesArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}. The value must be a fully rooted directory path..
        /// </summary>
        internal static string InvalidBaseDirectoryValue {
            get {
                return ResourceManager.GetString("InvalidBaseDirectoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not using a managed identity, all of these options are required: {0}, {1}, and {2}..
        /// </summary>
        internal static string InvalidClientSecretCredential {
            get {
                return ResourceManager.GetString("InvalidClientSecretCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path cannot be rooted when using a glob. Use a path relative to the working directory (or base directory, if used)..
        /// </summary>
        internal static string InvalidFileValue {
            get {
                return ResourceManager.GetString("InvalidFileValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed identity to authenticate to Azure Key Vault..
        /// </summary>
        internal static string ManagedIdentityOptionDescription {
            get {
                return ResourceManager.GetString("ManagedIdentityOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file or glob is required..
        /// </summary>
        internal static string MissingFileValue {
            get {
                return ResourceManager.GetString("MissingFileValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inputs found to sign..
        /// </summary>
        internal static string NoFilesToSign {
            get {
                return ResourceManager.GetString("NoFilesToSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files do not exist.  Try using a different {0} value or a fully qualified file path..
        /// </summary>
        internal static string SomeFilesDoNotExist {
            get {
                return ResourceManager.GetString("SomeFilesDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID to authenticate to Azure Key Vault..
        /// </summary>
        internal static string TenantIdOptionDescription {
            get {
                return ResourceManager.GetString("TenantIdOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to an Azure Key Vault..
        /// </summary>
        internal static string UrlOptionDescription {
            get {
                return ResourceManager.GetString("UrlOptionDescription", resourceCulture);
            }
        }
    }
}
