//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sign.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CertificateStoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificateStoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sign.Cli.CertificateStoreResources", typeof(CertificateStoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX, P7B, or CER file containing a certificate and potentially a private key..
        /// </summary>
        internal static string CertificateFileOptionDescription {
            get {
                return ResourceManager.GetString("CertificateFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for certificate file..
        /// </summary>
        internal static string CertificatePasswordOptionDescription {
            get {
                return ResourceManager.GetString("CertificatePasswordOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Service Provider containing the private key container. Requires /k and optionally /km..
        /// </summary>
        internal static string CspOptionDescription {
            get {
                return ResourceManager.GetString("CspOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key container name..
        /// </summary>
        internal static string KeyContainerOptionDescription {
            get {
                return ResourceManager.GetString("KeyContainerOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Service Provider missing.  Use /csp to specify a CSP..
        /// </summary>
        internal static string MissingCspError {
            get {
                return ResourceManager.GetString("MissingCspError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key container name missing. Use /k to specify a key container name..
        /// </summary>
        internal static string MissingPrivateKeyContainerError {
            get {
                return ResourceManager.GetString("MissingPrivateKeyContainerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA-1 thumbprint used to identify a certificate..
        /// </summary>
        internal static string Sha1ThumbprintOptionDescription {
            get {
                return ResourceManager.GetString("Sha1ThumbprintOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a machine-level private key container.  (The default is user-level.).
        /// </summary>
        internal static string UseMachineKeyContainerOptionDescription {
            get {
                return ResourceManager.GetString("UseMachineKeyContainerOptionDescription", resourceCulture);
            }
        }
    }
}
