trigger:
  branches:
    include:
      - master
      - rel/*
  paths:
    include:
      - src/SignService/*
      - .editorconfig
      - .vsts.service.ci.yml
      - version.json

queue: Hosted VS2017
variables: 
  BuildConfiguration: Release

steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- powershell: |
    # Restore
    msbuild /t:restore SignService.sln 

    # Copy sdk files locally before build
    msbuild src/SignService/SignService.csproj /t:PrebuildScript /p:Configuration=$(BuildConfiguration)

    # Build service
    msbuild src/SignService/SignService.csproj /p:Configuration=$(BuildConfiguration) /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\website\" 

  displayName: Build / Publish Service

- task: PublishBuildArtifacts@1
  displayName: Publish SignService Artifact
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\website
    artifactType: container
    artifactName: SignService