trigger:
  branches:
    include:
      - main
      - rel/*
  paths:
    include:
      - src/SignService/*
      - scripts/Install-WindowsSdkISO.ps1
      - .editorconfig
      - azure-pipelines.server.yml
      - version.json

pr:
  branches:
    include:
      - main
      - rel/*
  paths:
    include:
      - src/SignService/*
      - scripts/Install-WindowsSdkISO.ps1
      - .editorconfig
      - azure-pipelines.server.yml
      - version.json

pool:
  vmImage: windows-2022

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  TreatWarningsAsErrors: true

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 6.x'
  inputs:
    version: 6.x

- task: DotNetCoreCLI@2
  displayName: Copy sdk files locally before build
  inputs:
    command: custom
    projects: src/SignService/SignService.csproj
    custom: msbuild
    arguments: '/p:Configuration=$(BuildConfiguration) /t:PrebuildScript'

- task: DotNetCoreCLI@2
  displayName: Build and Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/SignService/SignService.csproj
    arguments: '-c $(BuildConfiguration) --output $(build.artifactstagingdirectory)\website\ -r win10-x86'
    zipAfterPublish: True

- publish: $(Build.ArtifactStagingDirectory)\website
  displayName: Publish SignService Artifact
  artifact: SignService

- task: AzureRmWebAppDeployment@4
  displayName: Deploy SignService
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    appType: webApp
    ConnectionType: AzureRM
    ConnectedServiceName: 'Speedy-geek AzureRm'
    ResourceGroupName: 'SignService_website'
    WebAppName: 'speedygeeksign'
    Package: '$(Build.ArtifactStagingDirectory)\website\SignService.zip'
    AppSettings: '-ASPNETCORE_HOSTINGSTARTUP__KEYVAULT__CONFIGURATIONENABLED true -ASPNETCORE_HOSTINGSTARTUP__KEYVAULT__CONFIGURATIONVAULT https://speedygeeksignkvo4oya.vault.azure.net/'
    ConfigurationSettings: '-use32BitWorkerProcess true'