//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sign.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sign.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument cannot be empty..
        /// </summary>
        internal static string ArgumentCannotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing SignTool job with {count} files..
        /// </summary>
        internal static string AzureSignToolSignatureProviderSigning {
            get {
                return ResourceManager.GetString("AzureSignToolSignatureProviderSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate is expired..
        /// </summary>
        internal static string CertificateIsExpired {
            get {
                return ResourceManager.GetString("CertificateIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate is not yet time valid..
        /// </summary>
        internal static string CertificateIsNotYetTimeValid {
            get {
                return ResourceManager.GetString("CertificateIsNotYetTimeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application manifest &apos;{0}&apos; contains invalid target path &apos;{1}&apos;..
        /// </summary>
        internal static string ClickOnceApplicationManifestInvalidTargetPath {
            get {
                return ResourceManager.GetString("ClickOnceApplicationManifestInvalidTargetPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application manifest &apos;{0}&apos; contains a required file reference without a target path..
        /// </summary>
        internal static string ClickOnceApplicationManifestMissingTargetPath {
            get {
                return ResourceManager.GetString("ClickOnceApplicationManifestMissingTargetPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to access source candidate &apos;{2}&apos; for target path &apos;{1}&apos; in application manifest &apos;{0}&apos;..
        /// </summary>
        internal static string ClickOnceApplicationManifestPayloadProbeFailed {
            get {
                return ResourceManager.GetString("ClickOnceApplicationManifestPayloadProbeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to read application manifest &apos;{0}&apos;..
        /// </summary>
        internal static string ClickOnceApplicationManifestReadFailed {
            get {
                return ResourceManager.GetString("ClickOnceApplicationManifestReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application manifest &apos;{0}&apos; references required file &apos;{1}&apos;, but it could not be found..
        /// </summary>
        internal static string ClickOnceApplicationManifestRequiredFileNotFound {
            get {
                return ResourceManager.GetString("ClickOnceApplicationManifestRequiredFileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve files referenced by application manifest &apos;{0}&apos;..
        /// </summary>
        internal static string ClickOnceApplicationManifestResolveFailed {
            get {
                return ResourceManager.GetString("ClickOnceApplicationManifestResolveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment manifest &apos;{0}&apos; references application manifest &apos;{1}&apos;, but the file does not exist..
        /// </summary>
        internal static string ClickOnceDeploymentManifestApplicationManifestNotFound {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestApplicationManifestNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to access launcher candidate &apos;{0}&apos; associated with deployment manifest &apos;{1}&apos;..
        /// </summary>
        internal static string ClickOnceDeploymentManifestLauncherProbeFailed {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestLauncherProbeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment manifest &apos;{0}&apos; does not identify an application manifest..
        /// </summary>
        internal static string ClickOnceDeploymentManifestMissingEntryPoint {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestMissingEntryPoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to read deployment manifest &apos;{0}&apos;..
        /// </summary>
        internal static string ClickOnceDeploymentManifestReadFailed {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to read application manifest &apos;{0}&apos; referenced by deployment manifest &apos;{1}&apos;..
        /// </summary>
        internal static string ClickOnceDeploymentManifestReferencedApplicationReadFailed {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestReferencedApplicationReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; referenced by deployment manifest &apos;{1}&apos; is not an application manifest..
        /// </summary>
        internal static string ClickOnceDeploymentManifestReferencedApplicationWrongType {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestReferencedApplicationWrongType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve files referenced by deployment manifest &apos;{0}&apos;..
        /// </summary>
        internal static string ClickOnceDeploymentManifestResolveFailed {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestResolveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to access setup bootstrapper candidate &apos;{0}&apos; associated with deployment manifest &apos;{1}&apos;..
        /// </summary>
        internal static string ClickOnceDeploymentManifestSetupProbeFailed {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestSetupProbeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment manifest &apos;{0}&apos; did not resolve its referenced application manifest &apos;{1}&apos;..
        /// </summary>
        internal static string ClickOnceDeploymentManifestUnresolvedApplicationManifest {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestUnresolvedApplicationManifest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment manifest &apos;{0}&apos; must contain exactly one non-prerequisite application manifest reference and no file references..
        /// </summary>
        internal static string ClickOnceDeploymentManifestUnsupportedReferences {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestUnsupportedReferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not a deployment manifest..
        /// </summary>
        internal static string ClickOnceDeploymentManifestWrongType {
            get {
                return ResourceManager.GetString("ClickOnceDeploymentManifestWrongType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Signing Mage job with {count} files..
        /// </summary>
        internal static string ClickOnceSignatureProviderSigning {
            get {
                return ResourceManager.GetString("ClickOnceSignatureProviderSigning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare file &apos;{0}&apos; for the signing operation..
        /// </summary>
        internal static string ClickOnceStagingCopyFailed {
            get {
                return ResourceManager.GetString("ClickOnceStagingCopyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source files &apos;{0}&apos; and &apos;{1}&apos; have conflicting target paths &apos;{2}&apos; and &apos;{3}&apos;..
        /// </summary>
        internal static string ClickOnceStagingDestinationCollision {
            get {
                return ResourceManager.GetString("ClickOnceStagingDestinationCollision", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to rename file &apos;{0}&apos; while updating manifest file information..
        /// </summary>
        internal static string ClickOnceStagingMappedSuffixFailed {
            get {
                return ResourceManager.GetString("ClickOnceStagingMappedSuffixFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source file &apos;{0}&apos; is referenced with conflicting target paths &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string ClickOnceStagingReferenceDestinationConflict {
            get {
                return ResourceManager.GetString("ClickOnceStagingReferenceDestinationConflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manifest target path &apos;{0}&apos; for source file &apos;{1}&apos; is invalid or unsupported..
        /// </summary>
        internal static string ClickOnceStagingUnsafeTargetPath {
            get {
                return ResourceManager.GetString("ClickOnceStagingUnsafeTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {fileName} returned the error {error}.
        /// </summary>
        internal static string CliStandardError {
            get {
                return ResourceManager.GetString("CliStandardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {fileName} returned the output {output}.
        /// </summary>
        internal static string CliStandardOutput {
            get {
                return ResourceManager.GetString("CliStandardOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating directory {path}..
        /// </summary>
        internal static string CreatingDirectory {
            get {
                return ResourceManager.GetString("CreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {path} deleted..
        /// </summary>
        internal static string DeletedDirectory {
            get {
                return ResourceManager.GetString("DeletedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory {path}..
        /// </summary>
        internal static string DeletingDirectory {
            get {
                return ResourceManager.GetString("DeletingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {path} still exists..
        /// </summary>
        internal static string DirectoryNotDeleted {
            get {
                return ResourceManager.GetString("DirectoryNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing AppInstaller job with {count} files..
        /// </summary>
        internal static string EditingAppInstaller {
            get {
                return ResourceManager.GetString("EditingAppInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error occurred during VSIX signing..
        /// </summary>
        internal static string ErrorSigningVsix {
            get {
                return ResourceManager.GetString("ErrorSigningVsix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while attempting to delete directory {path}..
        /// </summary>
        internal static string ExceptionWhileDeletingDirectory {
            get {
                return ResourceManager.GetString("ExceptionWhileDeletingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple private key containers provided. Use either /k for user stores or /km for machine stores..
        /// </summary>
        internal static string MultiplePrivateKeyContainersError {
            get {
                return ResourceManager.GetString("MultiplePrivateKeyContainersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key container missing while using /csp. Use /k or /km to provide a key container..
        /// </summary>
        internal static string NoPrivateKeyContainerError {
            get {
                return ResourceManager.GetString("NoPrivateKeyContainerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting container {ContainerFilePath} to {DirectoryPath}..
        /// </summary>
        internal static string OpeningContainer {
            get {
                return ResourceManager.GetString("OpeningContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} timed out and could not be killed..
        /// </summary>
        internal static string ProcessCouldNotBeKilled {
            get {
                return ResourceManager.GetString("ProcessCouldNotBeKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {fileName} took too long to respond. The process exit code is {exitCode}..
        /// </summary>
        internal static string ProcessDidNotExitInTime {
            get {
                return ResourceManager.GetString("ProcessDidNotExitInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} took too long to respond. The process exit code is {1}. Arguments: {2}.
        /// </summary>
        internal static string ProcessDidNotExitInTimeWithArguments {
            get {
                return ResourceManager.GetString("ProcessDidNotExitInTimeWithArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {fileName} with parameters: &apos;{args}&apos;..
        /// </summary>
        internal static string RunningCli {
            get {
                return ResourceManager.GetString("RunningCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding container {ContainerFilePath} from {DirectoryPath}..
        /// </summary>
        internal static string SavingContainer {
            get {
                return ResourceManager.GetString("SavingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignAsync called for {filePath}. Using {localFilePath} locally..
        /// </summary>
        internal static string SignAsyncCalled {
            get {
                return ResourceManager.GetString("SignAsyncCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing attempt #{attempt} of {maxAttempts} attempts after {seconds} s..
        /// </summary>
        internal static string SigningAttempt {
            get {
                return ResourceManager.GetString("SigningAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign {0}..
        /// </summary>
        internal static string SigningFailed {
            get {
                return ResourceManager.GetString("SigningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign. Attempts exceeded..
        /// </summary>
        internal static string SigningFailedAfterAllAttempts {
            get {
                return ResourceManager.GetString("SigningFailedAfterAllAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing failed with error {errorCode}..
        /// </summary>
        internal static string SigningFailedWithError {
            get {
                return ResourceManager.GetString("SigningFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing {filePath}..
        /// </summary>
        internal static string SigningFile {
            get {
                return ResourceManager.GetString("SigningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing {filePath} succeeded..
        /// </summary>
        internal static string SigningSucceeded {
            get {
                return ResourceManager.GetString("SigningSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed in {millseconds} ms..
        /// </summary>
        internal static string SigningSucceededWithTimeElapsed {
            get {
                return ResourceManager.GetString("SigningSucceededWithTimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting {filePath} for signing..
        /// </summary>
        internal static string SubmittingFileForSigning {
            get {
                return ResourceManager.GetString("SubmittingFileForSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing VsixSignTool job with {count} files..
        /// </summary>
        internal static string VsixSignatureProviderSigning {
            get {
                return ResourceManager.GetString("VsixSignatureProviderSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified {0} is invalid..
        /// </summary>
        internal static string VSIXSignToolOpcContentTypeInvalid {
            get {
                return ResourceManager.GetString("VSIXSignToolOpcContentTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown signing algorithm..
        /// </summary>
        internal static string VSIXSignToolUnknownSigningAlgorithm {
            get {
                return ResourceManager.GetString("VSIXSignToolUnknownSigningAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm selected is not supported..
        /// </summary>
        internal static string VSIXSignToolUnsupportedAlgorithm {
            get {
                return ResourceManager.GetString("VSIXSignToolUnsupportedAlgorithm", resourceCulture);
            }
        }
    }
}
