name: Build and Sign

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Build steps  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        
    - name: Build Package
      run: dotnet pack --configuration Release src/AClassLibrary/AClassLibrary.csproj
    
    # Publish the artifacts to sign and the file list, if any, as artifacts for the signing stage
    - name: Upload signing file list
      uses: actions/upload-artifact@v3
      with:
        name: config
        path: config
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BuildArtifacts
        path: src/AClassLibrary/bin/Release/**/*.nupkg
    
  sign:
    needs: build
    runs-on: windows-latest # Code signing must run on a Windows agent for Authenticode signing (dll/exe)
    if: ${{ github.ref == 'refs/heads/main' }} # Only run this job on pushes to the main branch
    permissions:
      id-token: write # Required for requesting the JWT
      
    steps:

    # Download signing configuration and artifacts
    - name: Download signing config
      uses: actions/download-artifact@v3
      with:
        name: config
        path: config
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: BuildArtifacts
        path: BuildArtifacts
    
    # .NET is required on the agent for the tool to run
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    # Install the code signing tool    
    - name: Install Sign CLI tool
      run: dotnet tool install --tool-path . --prerelease sign
    
    # Login to Azure using a ServicePrincipal configured to authenticate agaist a GitHub Action
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        allow-no-subscriptions: true
        client-id: ${{ secrets.AZURE_CLIENT_ID }} # This does not need to be a secret and is just a placeholder
        tenant-id: ${{ secrets.AZURE_TENANT_ID }} # This does not need to be a secret and is just a placeholder

    # Run the signing command
    - name: Sign artifacts
      shell: pwsh
      run: >
        ./sign code artifact-signing
        **/*.nupkg
        --base-directory "${{ github.workspace }}/BuildArtifacts"
        --file-list "${{ github.workspace }}/config/filelist.txt"
        --publisher-name "Contoso"
        --description "One Sign CLI demo"
        --description-url "https://github.com/dotnet/sign"
        --azure-credential-type "azure-cli"
        --artifact-signing-endpoint "${{ secrets.ARTIFACT_SIGNING_ENDPOINT }}"
        --artifact-signing-account "${{ secrets.ARTIFACT_SIGNING_ACCOUNT }}"
        --artifact-signing-certificate-profile "${{ secrets.ARTIFACT_SIGNING_CERTIFICATE_PROFILE }}"
        --certificate-output "${{ runner.temp }}\signing-certificate.cer"

    # Make the public certificate path available to later steps in this job.
    - name: Publish signing certificate path
      id: signing-certificate
      shell: pwsh
      run: '"certificate_file=${{ runner.temp }}\signing-certificate.cer" >> $env:GITHUB_OUTPUT'

    - name: Use signing certificate
      shell: pwsh
      run: Get-PfxCertificate -FilePath "${{ steps.signing-certificate.outputs.certificate_file }}"
    
    # Publish the signed packages
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SignedArtifacts
        path: BuildArtifacts
